apiVersion: apps/v1
kind: Deployment
metadata:
 name: httpd-deployment-prod
 namespace: prod
spec:
 selector:
   matchLabels:
    type: web
 replicas: 2
 template:
   metadata:
     labels:
       type: web
   spec:
    containers:
    - name: container
      image: xc7230/hello:latest
      envFrom:
      ports:
      - containerPort: 80
      resources:
        requests:
          cpu: 100m
        limits:
          cpu: 200m